database:
  host: localhost
  port: 5432
  user: airflow
  password: airflow
  dbname: airflow

paths:
  raw_data: data/raw/
  processed_data: data/processed/cleaned_data.csv
  spark_configs: spark-configs/